language: ruby
rvm:
- 2.2.0
sudo: false
git:
  submodules: false
script: "./go ci_build"
notifications:
  email:
    recipients:
    - eric.mill@gsa.gov
    - hillary.hartley@gsa.gov
    - gregory.boone@gsa.gov
    on_success: change
    on_failure: change
branches:
  only:
  - staging
  - production
  - redeploy
deploy:
  provider: s3
  access_key_id: AKIAI4LCAXVBDV5DIESQ
  secret_access_key:
    secure: O/4NyKjbM9zFJSFdXbk9lZiaHtUEhtfTRZO3Ryeb+iQi+UCDDzD6N0gK9SwdzxGmAUkWmYKfH8ho4jTNpX/lwds6nh/2qSzAq2FKI8y7sj2vBABXFdvuehn1MBrxeZ4ZttLzSSdqFw9NWfQzFm8fdWfxI+wo2ony4BEPcUaCYjM=
  bucket: 18f-site-ci-build
  local-dir: _site
  upload-dir: $TRAVIS_COMMIT
  acl: public_read
  on:
    repo: 18F/18f.gsa.gov
